upgrade to commons-digester3
jenkinsci/vectorcast-coverage-plugin pull request #4
Opened 2021-04-30 20:32 UTC by car-roll

upgrade to commons-digester3. Follow up of https://github.com/jenkinsci/jenkins/pull/5320

ping @nbelliot @TimSVector 

- [x] Make sure you are opening from a **topic/feature/bugfix branch** (right side) and not your master branch!
- [x] Ensure that the pull request title represents the desired changelog entry
- [x] Please describe what you did
- [ ] Link to relevant issues in GitHub or Jira
- [x] Link to relevant pull requests, esp. upstream and downstream changes
- [ ] Ensure you have provided tests - that demonstrates feature works or fixes the issue

2021-05-03 10:31 UTC, alecharp approved these changes

2021-05-03 14:26 UTC, MRamonLeon approved these changes

2021-05-03 15:31 UTC, andrewvaughanj commented
@car-roll @alecharp @MRamonLeon: this PR seems to make the VectorCAST plugin align with https://github.com/jenkinsci/jenkins/pull/5320

What’s the impact of us merging this before #5320 gets merged in?

Does `commons-digester3` already exist in a fully-released Jenkins?

2021-05-03 16:25 UTC, car-roll commented
@andrewvaughanj there should be no impact of merging in this early as `commons-digester3` is not a part of Jenkins. https://github.com/jenkinsci/jenkins/pull/5320 is removing `commons-digester:2.1` from Jenkins so that plugins will have to explicitly call out the library in the dependencies.

2021-05-03 17:04 UTC, andrewvaughanj commented on src/main/java/com/vectorcast/plugins/vectorcastcoverage/CoverageReport.java
> +            createDigester(!Boolean.getBoolean(this.getClass().getName() + ".UNSAFE")).parse(is);
AFAIK, the `vectorcast-coverage-plugin` does not have any `UNSAFE` classes -- given this, what's the impact of this now defaulting to `createDigester(true)` (which then does the `digester.setFeature` stuff)?

Basically, this plugin is deployed a lot on on-prem installations where outside access might not be allowed; I'm worried this change will now mean that all `createDigester` calls end-up with `SAXException`.

2021-05-03 17:05 UTC, andrewvaughanj requested changes
No changes necessary, but there are outstanding questions on the PR.

2021-05-04 09:24 UTC, alecharp commented on src/main/java/com/vectorcast/plugins/vectorcastcoverage/CoverageReport.java
> +            createDigester(!Boolean.getBoolean(this.getClass().getName() + ".UNSAFE")).parse(is);
I understand that for now there is no unsafe classes, but this is a good way to opt out of the security if ever needed (shouldn't be the case). This is a typical security pattern, to have a switch to return to the safe behaviour as before the fix. 

There is no danger of having this.

2021-05-04 10:25 UTC, andrewvaughanj commented on src/main/java/com/vectorcast/plugins/vectorcastcoverage/CoverageReport.java
> +            createDigester(!Boolean.getBoolean(this.getClass().getName() + ".UNSAFE")).parse(is);
My concern is this code:

```
            try {
                digester.setFeature("http://apache.org/xml/features/disallow-doctype-decl", true);
                digester.setFeature("http://xml.org/sax/features/external-general-entities", false);
                digester.setFeature("http://xml.org/sax/features/external-parameter-entities", false);
                digester.setFeature("http://apache.org/xml/features/nonvalidating/load-external-dtd", false);
            } catch (ParserConfigurationException ex) {
                throw new SAXException("Failed to securely configure xml digester parser", ex);
            }
```

which is now exercised "by default" (because we have no `UNSAFE` classes).

What happens if, e.g., `http://apache.org/xml/features/disallow-doctype-decl` is not accessible (for example, the CI machine cannot access any outside resources **at all**)?

Looking at this code, we now would do this:

- `createDigester(true)`
- `digester.setFeature("http://apache.org/xml/features/disallow-doctype-decl", true);` <-- this `throw`s due to being unable to access these outside URLs
- which leads to `throw new SAXException("Failed to securely configure xml digester parser` as part of the `try`-`catch`
- which leads to `throw new IOException2("Failed to parse XML:" + idx,e)` in the "main code" as part of the `try`-`catch`

Or have I misunderstood?

2021-05-04 10:29 UTC, andrewvaughanj commented on src/main/java/com/vectorcast/plugins/vectorcastcoverage/CoverageReport.java
> +            createDigester(!Boolean.getBoolean(this.getClass().getName() + ".UNSAFE")).parse(is);
Maybe I have misunderstood; does `digester.setFeature("http://apache.org/xml/features/disallow-doctype-decl", true);` "reach outside" or is this just saying that this DTD is "built-in" to the digester?

2021-05-04 20:52 UTC, car-roll commented on src/main/java/com/vectorcast/plugins/vectorcastcoverage/CoverageReport.java
> +            createDigester(!Boolean.getBoolean(this.getClass().getName() + ".UNSAFE")).parse(is);
@andrewvaughanj You're right, the strings you see (`"http://apache.org/xml/features/disallow-doctype-decl"`) are just standard `SAX2` feature flags ([see here](http://commons.apache.org/proper/commons-digester/apidocs/org/apache/commons/digester3/Digester.html#setFeature(java.lang.String,%20boolean)) and [here](https://docs.oracle.com/javase//1.5.0/docs/api/org/xml/sax/package-summary.html)) 

These links won't resolve anywhere meaningful and, coincidentally enough, `disallow-doctype-decl` doesn't resolve just like in your scenario.

2021-05-04 22:04 UTC, andrewvaughanj commented on src/main/java/com/vectorcast/plugins/vectorcastcoverage/CoverageReport.java
> +            createDigester(!Boolean.getBoolean(this.getClass().getName() + ".UNSAFE")).parse(is);
Thanks, I appreciate the clarification!

2021-05-04 22:04 UTC, andrewvaughanj approved these changes
LGTM! Thanks, @car-roll!

2021-05-04 22:05 UTC, andrewvaughanj commented
@TimSVector, @nbelliot: these changes look good to me; do you want me to merge?

2021-05-05 12:45 UTC, nbelliot commented
Thanks for reviewing, @andrewvaughanj. I am going to create a branch off of master to run the change through our CI before merging it into master. I'll take it from here. Thanks, again.

2021-05-05 12:46 UTC, andrewvaughanj commented
All yours!

2021-05-05 19:47 UTC, nbelliot commented
Test suite is clean. Thanks, everyone.

2021-05-05 19:47 UTC, merged

2021-05-06 07:47 UTC, MRamonLeon commented
Thank you very much @nbelliot . May I ask you to cut a release with this change?

2021-05-06 12:35 UTC, nbelliot commented
@MRamonLeon: We plan on performing a release soon along with some of unrelated additional changes.